default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>

development:
  <<: *default
  database: poker_api_development

test:
  <<: *default
  database: poker_api_test

production:
  <<: *default
  database: poker_api_production
