default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myuser         # coloque aqui o mesmo usuário que você criou no psql
  password: mypassword     # coloque aqui a senha que você definiu
  host: localhost

development:
  <<: *default
  database: poker_api_development

test:
  <<: *default
  database: poker_api_test

production:
  <<: *default
  database: poker_api_production
  username: poker_api
  password: <%= ENV['POKER_API_DATABASE_PASSWORD'] %>
